apiVersion: apps/v1
kind: Deployment
metadata:
  name: bartender-backend
  labels:
    app: bartender-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bartender-backend
  template:
    metadata:
      labels:
        app: bartender-backend
    spec:
      containers:
        - name: bartender-backend
          image: bartender-backend
---
apiVersion: v1
kind: Service
metadata:
  name: bartender-backend
spec:
  selector:
    app: bartender-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001